name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout

      uses: git@github.com:knnupl

    - name: Deployment

      uses: git@github.com:knnupl

      with:

        host: ${{ secrets.SSH_HOST }}

        key: ${{ secrets.SSH_PRIVATE_KEY }}

        username: ${{ secrets.SSH_USERNAME }}

        script: |

          cd /var/www/html/

          git checkout -f 

          git pull
